WXDX/W4D2/rent_a_cat/config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
  resources :cat_rental_requests, only: [:new, :create]
end

WXDX/W4D2/rent_a_cat/app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many(
    :cat_rental_requests,
    class_name: "CatRentalRequest",
    dependent: :destroy
    )

  validates(
    :name,
    :birth_date,
    :color,
    :sex,
    presence: true
  )
end

WXDX/W4D2/rent_a_cat/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  # STATUS_STATES = %w(APPROVED DENIED PENDING)

  belongs_to :cat

  validates(
    :cat_id,
    :start_date,
    :end_date,
    :status,
    presence: true
  )

  # validates :status, inclusion: STATUS_STATES
  # validate :start_must_come_before_end
  # validate :does_not_overlap_approved_request

  def overlapping_requests
  end

  def overlapping_approved_requests
  end

end

WXDX/W4D2/rent_a_cat/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cat_url(@cat_rental_request.cat)
    else
      # flash.now[:errors] = @cat_rental_request.errors.full_messages
      render :new
    end
  end

  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end
end

WXDX/W4D2/rent_a_cat/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    # render json: cats
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    # render json: cats
    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    # render json: "creating cat"
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_params)
        redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :color, :sex, :description, :birth_date)
  end
end

WXDX/W4D2/rent_a_cat/app/views/cat_rental_requests/new.html.erb
<h1> create a request! </h1>

<form action="<%= cat_rental_requests_url %>" method="post">
  <label for="cat_rental_request_cat_id">Cat</label>
  <select id="cat_rental_request_cat_id" name="cat_rental_request[cat_id]">

    <option disabled selected>--  Select Cat--</option>
    <% Cat.all.each do |cat| %>
      <% selected = @cat_rental_request.cat_id == cat.id %>
    <option <%= selected ? "selected" : "" %>
            value="<%= cat.id %>">
        <%= cat.name %>
      </option>
    <% end %>
  </select>

<br>

  <label for="start_date">Start Date</label>
  <input id="start_date" type="date" name="cat_rental_request[start_date]" value="<%= @cat_rental_request.start_date %>">

<br>

<label for="end_date">End Date</label>
<input id="end_date" type="date" name="cat[end_date]" value="<%= @cat_rental_request.end_date %>">

<!-- <br>

<label for="status">Status</label>
<input id="status" type="text" name="cat[status]" value="<%= @cat_rental_request.status %>"> -->


  <input type="submit">

</form>

WXDX/W4D2/rent_a_cat/app/views/cats/_cat.html.erb
<li>
  <%= cat.name %> <%= cat.color %> <%= cat.sex %>
</li>

WXDX/W4D2/rent_a_cat/app/views/cats/_form.html.erb
<h1>dis be da cool form partial</h1>

<% if action == :edit %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

<br>

  <label for="sex">Sex</label>
  <input id="cat_sex_male" type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : ""%> >
  <label for="cat_sex_male">Male</label>

  <input id="cat_sex_female" type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : ""%> >
  <label for="cat_sex_female">Female</label>

<br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled <%= cat.color ? "" : "selected"%>>-- Please Select --</option>
    <option value="black" <%= cat.color == "black" ? "selected" : ""%> >Black</option>
    <option value="brown" <%= cat.color == "brown" ? "selected" : ""%> >Brown</option>
    <option value="orange" <%= cat.color == "orange" ? "selected" : ""%> >Orange</option>
  </select>

<br>

  <label for="birth_date">Birthdate</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

<br>

  <label for="description">Description</label>
  <textarea name="cat[description]">
    <%= cat.description %>
  </textarea>
  <input type="submit" value= "<%= (action == :edit) ? "update cat" : "add ca1t"%>">

</form>

WXDX/W4D2/rent_a_cat/app/views/cats/edit.html.erb
<h1> u be changin dis cat </h1>

<%= render 'form', cat: @cat, action: :edit %>

<!-- <form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= @cat.name %>">

<br>

  <label for="sex">Sex</label>
  <input id="cat_sex_male" type="radio" name="cat[sex]" value="M" <%= @cat.sex == "M" ? "checked" : ""%> >
  <label for="cat_sex_male">Male</label>

  <input id="cat_sex_female" type="radio" name="cat[sex]" value="F" <%= @cat.sex == "F" ? "checked" : ""%> >
  <label for="cat_sex_female">Female</label>

<br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled>-- Please Select --</option>
    <option value="black" <%= @cat.color == "black" ? "selected" : ""%> >Black</option>
    <option value="brown" <%= @cat.color == "brown" ? "selected" : ""%> >Brown</option>
    <option value="orange" <%= @cat.color == "orange" ? "selected" : ""%> >Orange</option>
  </select>

<br>

  <label for="birth_date">Birthdate</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">

<br>

  <label for="description">Description</label>
  <textarea name="cat[description]">
    <%= @cat.description %>
  </textarea>
  <input type="submit" value="update cat">

</form> -->

WXDX/W4D2/rent_a_cat/app/views/cats/index.html.erb
<style>
html {
  background: url(https://images.pexels.com/photos/126407/pexels-photo-126407.jpeg?w=940&h=650&auto=compress&cs=tinysrgb) no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
</style>

<h1> dis be all teh cats </h1>

<ul>
  <%= render @cats %>
</ul>

WXDX/W4D2/rent_a_cat/app/views/cats/new.html.erb
<h1> u be creatin dis new cat </h1>

<%= render 'form', action: :new, cat: @cat %>
<!-- <form action="<%= cats_url %>" method="post">
  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]">

<br>

  <label for="sex">Sex</label>
  <input id="cat_sex_male" type="radio" name="cat[sex]" value="M">

  <label for="cat_sex_male">Male</label>
  <input id="cat_sex_female" type="radio" name="cat[sex]" value="F">

  <label for="cat_sex_female">Female</label>

<br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled selected>-- Please Select --</option>
    <option value="black">Black</option>
    <option value="brown">Brown</option>
    <option value="orange">Orange</option>
  </select>

<br>

  <label for="birth_date">Birthdate</label>
  <input id="birth_date" type="date" name="cat[birth_date]">

<br>

  <label for="description">Description</label>
  <textarea name="cat[description]"></textarea>
  <input type="submit" value="Add cat">

</form> -->

WXDX/W4D2/rent_a_cat/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<h3>Birthdate: <%= @cat.birth_date %></h3>
<h3>Color: <%= @cat.color %></h3>
<!-- <h3>Age: <%#= @cat.age %></h3> -->
<h3>Sex: <%= @cat.sex %></h3>
<h3>Description: <%= @cat.description %></h3>
<h3>Rental Requests:</h3>
<h1>
  <%= @cat_rental_request %>
<table>
  <tr>
    <th> Start Date</th>
    <th> End Date</th>
    <th> Status</th>
  </tr>
</table>

WXDX/W4D2/rent_a_cat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentACat</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>